fixed travis error by fixing test-stripe.py, added donation_successful page
ARM-open/arm-open.github.io pull request #12
Opened 2017-06-02 17:59 UTC by rohithsivakumar

-This PR fixes the error that was showing up in Travis, caused by a syntax error in test-stripe.py
-It also adds the donation_successful page that users are lead to after donating with the stripe form
-These changes were tested by running the app in localhost
<img width="1280" alt="screen shot 2017-06-02 at 1 39 28 pm" src="https://cloud.githubusercontent.com/assets/6231630/26738301/997b4764-479b-11e7-8589-f7cf6722c135.png">

2017-06-03 18:19 UTC, davidawad requested changes
I have a few changes to request but overall good work!

2017-06-03 18:19 UTC, DavidAwad commented on .travis.yml
> +    - STRIPE_SECRET_KEY="SAMPLESTRIPEKEY"
🔥

2017-06-03 18:19 UTC, DavidAwad commented on templates/donation_successful.html
> +	<!-- <link rel="stylesheet" href="../static/bower_components/font-awesome/css/font-awesome.min.css"> Resource style -->
o_0 
wait why are we using the font-awesome cdn and not the local one?

2017-06-03 18:19 UTC, DavidAwad commented on templates/donation_successful.html
> +<style>
use a separate css style sheet please :)

2017-06-03 18:19 UTC, DavidAwad commented on templates/donation_successful.html
> +-->
Why is google analytics commented out here?

2017-06-03 18:19 UTC, DavidAwad commented on templates/donation_successful.html
> +        		<h4>YOUR SUPPORT IS APPRECIATED</h4>
lol, was this really the copy dorie used in the pdf?

2017-06-03 18:19 UTC, DavidAwad commented on templates/donation_successful.html
> +        </header>
I think we can leverage jinja templating and avoid repeating so much html in multiple places. 

put this into a header.html and use jinja to `include` that file here and on `index.html`.

That way we only have to maintain one copy of how the header looks.

2017-06-03 18:40 UTC, rohithsivakumar commented on templates/donation_successful.html
> +	<!-- <link rel="stylesheet" href="../static/bower_components/font-awesome/css/font-awesome.min.css"> Resource style -->
I'm not sure, I just copy-pasted the code over from index.html's <head>, and that's how it was. Also, there's no static/bower_components directory in the repo

2017-06-03 18:41 UTC, rohithsivakumar commented on templates/donation_successful.html
> +-->
I wasn't sure if you wanted to use the same GA_ID from the index.html file, since this is a different page. So, I just commented it out for now

2017-06-03 18:58 UTC, DavidAwad commented on templates/donation_successful.html
> +	<!-- <link rel="stylesheet" href="../static/bower_components/font-awesome/css/font-awesome.min.css"> Resource style -->
*handled offline*

2017-06-03 18:59 UTC, DavidAwad commented on templates/donation_successful.html
> +-->
yes, use the same GA_ID it's fine :)

2017-06-03 20:43 UTC, DavidAwad commented on templates/donation_successful.html
> +        		<a href="#" target='_blank'><b class="link-button">Join Us</b></a>
broken link? Fill this in with any link you want from the other join us buttons, it just feels funny that this would be broken haha.

2017-06-06 20:30 UTC, DavidAwad commented
Last thing to iron out here is just to see if we can avoid requesting checkout.js multiple times. 
good work so far @rohithsivakumar

2017-06-07 23:36 UTC, merged